export const LOGIN_REQUEST_INITIATE = 'LOGIN_REQUEST_INITIATE';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const REGISTER_REQUEST_INITIATE = 'REGISTER_REQUEST_INITIATE';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE';

export const CREATE_BLOG_REQUEST_INITIATE = 'CREATE_BLOG_REQUEST_INITIATE';
export const CREATE_BLOG_REQUEST_SUCCESS = 'CREATE_BLOG_REQUEST_SUCCESS';
export const CREATE_BLOG_REQUEST_FAILURE = 'CREATE_BLOG_REQUEST_FAILURE';

export const GET_ALL_BLOG_REQUEST_INITIATE = 'GET_ALL_BLOG_REQUEST_INITIATE';
export const GET_ALL_BLOG_REQUEST_SUCCESS = 'GET_ALL_BLOG_REQUEST_SUCCESS';
export const GET_ALL_BLOG_REQUEST_FAILURE = 'GET_ALL_BLOG_REQUEST_FAILURE';
